#!/usr/bin/env python3
"""
Quick reference example showing how to use the thestatpy feature.

This demonstrates the pattern used in the class-timetable project.
"""

# ============================================================================
# SOURCE FILE STRUCTURE
# ============================================================================
# src/
#   ├── index.html              (main file with <import app="thestatpy"/>)
#   ├── assets/
#   │   ├── main.css
#   │   └── script.js
#   └── part/
#       ├── edit-modal.html     (external component)
#       └── about-modal.html    (external component)


# ============================================================================
# EXAMPLE 1: Basic Usage in HTML
# ============================================================================

html_with_thestatpy = """
<!DOCTYPE html>
<html>
<head>
    <title>App</title>
    <!-- This tag tells the build system to process <thestatpy> tags -->
    <import app="thestatpy"/>
</head>
<body>
    <main id="app">
        <!-- These tags will be replaced with content from external files -->
        <thestatpy html="part/edit-modal.html"></thestatpy>
        <thestatpy html="part/about-modal.html"></thestatpy>
    </main>
</body>
</html>
"""

# After processing, becomes:
processed_html = """
<!DOCTYPE html>
<html>
<head>
    <title>App</title>
    <import app="thestatpy"/>
</head>
<body>
    <main id="app">
        <!-- Content from part/edit-modal.html appears here -->
        <div id="editModal" class="modal hidden">
            <!-- Modal content -->
        </div>
        
        <!-- Content from part/about-modal.html appears here -->
        <div id="aboutModal" class="modal hidden">
            <!-- Modal content -->
        </div>
    </main>
</body>
</html>
"""


# ============================================================================
# EXAMPLE 2: Using the Standalone Processor
# ============================================================================

def example_standalone_usage():
    """
    Shows how to use the standalone processor programmatically.
    """
    import sys
    sys.path.insert(0, '.')
    from process_thestatpy import process_thestatpy
    import os
    
    # Read your HTML
    with open('src/index.html', 'r') as f:
        html = f.read()
    
    # Process thestatpy tags
    base_dir = os.path.dirname('src/index.html')
    processed = process_thestatpy(html, base_dir, verbose=True)
    
    # Save or use the result
    with open('output.html', 'w') as f:
        f.write(processed)


# ============================================================================
# EXAMPLE 3: Using in Build Pipeline
# ============================================================================

def example_build_integration():
    """
    Shows how thestatpy is automatically integrated in build.py.
    
    The build.py file does this automatically:
    """
    html_content = "..."  # Read from source file
    
    # 1. Process thestatpy tags first
    from process_thestatpy import process_thestatpy
    base_dir = "."
    content = process_thestatpy(html_content, base_dir)
    
    # 2. Then minify the result
    from minify_html import minify  # Using build dependencies
    minified = minify(content, minify_css=True, minify_js=True)
    
    # 3. Write to build directory
    with open('build/index.html', 'w') as f:
        f.write(minified)


# ============================================================================
# FILE LAYOUT WORKING WITH YOUR PROJECT
# ============================================================================

"""
Current structure in class-timetable:

src/
├── index.html                  <- Contains:
│                                 <import app="thestatpy"/>
│                                 <thestatpy html="part/edit-modal.html">
│                                 <thestatpy html="part/about-modal.html">
│
├── assets/
│   ├── main.css
│   ├── script.js
│   ├── landscape.css
│   ├── portrait.css
│   └── slide.css
│
├── part/
│   ├── edit-modal.html         <- External component
│   └── about-modal.html        <- External component
│
├── time-table.js
└── sw.js        (service worker)

build/                          <- Generated by build.py
├── index.html                 (with thestatpy tags replaced & minified)
├── assets/
├── part/
├── time-table.js
└── sw.js
"""


# ============================================================================
# COMMAND REFERENCE
# ============================================================================

"""
Process TheStatPy tags:
    python process_thestatpy.py src/index.html

Process and save to file:
    python process_thestatpy.py src/index.html output.html

Verbose output (debugging):
    python process_thestatpy.py -v src/index.html

Run full build with integrated thestatpy:
    python build.py

Get help:
    python process_thestatpy.py --help
"""


if __name__ == "__main__":
    print("This is a reference guide. See the docstrings for examples.")
    print("\nTo use, run:")
    print("  python process_thestatpy.py src/index.html")
    print("  python build.py")
