name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for Raising the issue, we assure you that wee will look into the solution very soon..."
        pr-message: "Congartulations for your first pull request, we will publish the changes once we complete the verification process."
